name: LoginToAzure

on:
  workflow_dispatch:

jobs:
    login:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Login to Azure
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true
    
        - name: Run Azure CLI command
          run: |
            az account show
            az vm list --output table
