name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
              name: list files
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - run: go version
            - uses: actions/setup-go@v5
              with:
                # go-version: '1.22'
                GO-VERSION-FILE: ./upper/go.mod
                cache-dependency-path: ./upper/go.sum
            - run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: ./upper
              name: build and test