name: upper-image

on:
    push:
        paths:
            - ".github/workflows/upper-image.yml"
            - "upper/**"
    workflow_dispatch: # manual

permissions:
    packages: write

jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: ./upper
                file: ./upper/Dockerfile
                tags: ghcr.io/${{ github.repository_owner }}/upper-image:latest
                push: true
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache