name: upper-image

on:
    push:
        paths:
            - ".github/workflows/upper-image.yml"
            - "upper/**"
    workflow_dispatch: # manual

permissions:
    packages: write

jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: docker --version
            - name: Build Docker Image
              run: docker image build -t upper
              working-directory: ./upper
            - name: test it
              run: docker run -d --name upper upper